name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn tsdx test --collectCoverage --coverageReporters 'cobertura'
     - name: OpenCover Badge Generator
        uses: danpetitt/open-cover-badge-generator-action@v1.0.9
        with:
          path-to-opencover-xml: coverage/**/cobertura-coverage.xml
          path-to-badges: ./
          minimum-coverage: 90
          commit-badges: false
          repo-token: ${{ secrets.CI_TOKEN }}